version: '2'
services:
  serverless:
    image: dockercloud/haproxy:1.6.7
    ports:
    - 8000:80
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - backend
  backend:
    build: .
    image: scrappy-serverless
    links:
    - redis
  redis:
    image: redis:4.0.1
